server:
  port: 8010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

spring:
  application:
    name: api
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/tpp?characterEncoding=utf-8
    username: root
    password: xxxxxx
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapping/*.xml

drawing:
  bed:
#    图片存储地址
    path: xxxxxxx